// This file is generated by scripts/import-bwiki-dex.mjs.
// Do not edit it by hand; run "npm run data:import" to refresh.

import type { AttributeMeta } from '../types'

export const attributes = [
  {
    "key": "ice",
    "nameZh": "冰",
    "nameEn": "Ice",
    "color": "#7fc6d9",
    "textColor": "#082029",
    "descriptionZh": "水系灭火冲机土 草冰龙系笑它苦\n草电出手克水系 火系机械没关系",
    "offense": {
      "0.5": [
        "fire",
        "ice",
        "mechanical"
      ],
      "2.0": [
        "grass",
        "ground",
        "dragon",
        "wing"
      ]
    },
    "defense": {
      "0.5": [
        "water",
        "light",
        "ice"
      ],
      "2.0": [
        "fire",
        "ground",
        "fighting",
        "mechanical"
      ]
    }
  },
  {
    "key": "grass",
    "nameZh": "草",
    "nameEn": "Grass",
    "color": "#62ad6b",
    "textColor": "#102112",
    "descriptionZh": "草系专治水光地 见火毒虫只能避 飞机龙也搞不定 \n 火冰毒虫翼来袭 草系遇见快闪避 水地电光不怕伤",
    "offense": {
      "0.5": [
        "fire",
        "dragon",
        "poison",
        "bug",
        "wing",
        "mechanical"
      ],
      "2.0": [
        "water",
        "ground"
      ]
    },
    "defense": {
      "0.5": [
        "water",
        "light",
        "ground",
        "electric"
      ],
      "2.0": [
        "fire",
        "ice",
        "poison",
        "bug",
        "wing"
      ]
    }
  },
  {
    "key": "bug",
    "nameZh": "虫",
    "nameEn": "Bug",
    "color": "#78a85a",
    "textColor": "#122015",
    "descriptionZh": "草恶幻系难遁形 虫刺连击破防强\n火翼当前应避战 草武阵里任横行",
    "offense": {
      "0.5": [
        "fire",
        "poison",
        "fighting",
        "wing",
        "cute",
        "ghost",
        "mechanical"
      ],
      "2.0": [
        "grass",
        "fantasy",
        "demon"
      ]
    },
    "defense": {
      "0.5": [
        "grass",
        "ice",
        "cute",
        "bug",
        "mechanical"
      ],
      "2.0": [
        "fire",
        "wing",
        "water",
        "ground"
      ]
    }
  },
  {
    "key": "ground",
    "nameZh": "地面",
    "nameEn": "Ground",
    "color": "#b88a55",
    "textColor": "#211508",
    "descriptionZh": "地系震火冰电毒 草武反手地成奴\n草水冰武机克制 普火翼电毒认输",
    "offense": {
      "0.5": [
        "grass",
        "fighting"
      ],
      "2.0": [
        "fire",
        "ice",
        "electric",
        "poison"
      ]
    },
    "defense": {
      "0.5": [
        "normal",
        "fire",
        "electric",
        "poison",
        "wing"
      ],
      "2.0": [
        "grass",
        "water",
        "ice",
        "fighting",
        "mechanical"
      ]
    }
  },
  {
    "key": "electric",
    "nameZh": "电",
    "nameEn": "Electric",
    "color": "#f2c849",
    "textColor": "#241b00",
    "descriptionZh": "电系遇水威力强 翼系更是难抵敌\n草系地系不怕电 龙系更加无压力",
    "offense": {
      "0.5": [
        "grass",
        "ground",
        "dragon",
        "electric"
      ],
      "2.0": [
        "water",
        "wing"
      ]
    },
    "defense": {
      "0.5": [
        "electric",
        "wing",
        "mechanical"
      ],
      "2.0": [
        "ground"
      ]
    }
  },
  {
    "key": "poison",
    "nameZh": "毒",
    "nameEn": "Poison",
    "color": "#a360a8",
    "textColor": "#ffffff",
    "descriptionZh": "毒系出手草萌慌 地毒幽械减伤强\n地恶幻系敲毒脑 草虫武毒萌扛伤",
    "offense": {
      "0.5": [
        "ground",
        "poison",
        "ghost",
        "mechanical"
      ],
      "2.0": [
        "grass",
        "cute"
      ]
    },
    "defense": {
      "0.5": [
        "grass",
        "poison",
        "bug",
        "fighting",
        "cute"
      ],
      "2.0": [
        "ground",
        "fantasy",
        "demon"
      ]
    }
  },
  {
    "key": "demon",
    "nameZh": "恶魔",
    "nameEn": "Demon",
    "color": "#6d617b",
    "textColor": "#ffffff",
    "descriptionZh": "萌系胆小怕恶魔 幽系同样被压制\n光系武系很正义 谁惧你的暗突袭",
    "offense": {
      "0.5": [
        "light",
        "fighting",
        "demon"
      ],
      "2.0": [
        "poison",
        "ghost",
        "cute"
      ]
    },
    "defense": {
      "0.5": [
        "ghost",
        "demon"
      ],
      "2.0": [
        "light",
        "fighting",
        "bug",
        "cute"
      ]
    }
  },
  {
    "key": "light",
    "nameZh": "光",
    "nameEn": "Light",
    "color": "#f5d86a",
    "textColor": "#251f08",
    "descriptionZh": "圣光净幽恶，冰草见它乐\n幽草打的痛，恶幻能抵抗",
    "offense": {
      "0.5": [
        "grass",
        "ice"
      ],
      "2.0": [
        "ghost",
        "demon"
      ]
    },
    "defense": {
      "0.5": [
        "fantasy",
        "demon"
      ],
      "2.0": [
        "grass",
        "ghost"
      ]
    }
  },
  {
    "key": "fantasy",
    "nameZh": "幻",
    "nameEn": "Fantasy",
    "color": "#9d78d9",
    "textColor": "#ffffff",
    "descriptionZh": "幻系最是摸不透 毒系武系均难敌\n光系照彻迷梦幻 机械戳穿假把戏",
    "offense": {
      "0.5": [
        "light",
        "fantasy",
        "mechanical"
      ],
      "2.0": [
        "poison",
        "fighting"
      ]
    },
    "defense": {
      "0.5": [
        "fighting",
        "fantasy"
      ],
      "2.0": [
        "ghost",
        "bug"
      ]
    }
  },
  {
    "key": "fire",
    "nameZh": "火",
    "nameEn": "Fire",
    "color": "#df6545",
    "textColor": "#ffffff",
    "descriptionZh": "火系暴躁烧草虫，冰系机械看他愁\n遇水遇地变狗熊，还有一位天敌龙",
    "offense": {
      "0.5": [
        "water",
        "ground",
        "dragon"
      ],
      "2.0": [
        "grass",
        "ice",
        "bug",
        "mechanical"
      ]
    },
    "defense": {
      "0.5": [
        "grass",
        "ice",
        "bug",
        "mechanical",
        "cute"
      ],
      "2.0": [
        "water",
        "ground"
      ]
    }
  },
  {
    "key": "mechanical",
    "nameZh": "机械",
    "nameEn": "Mechanical",
    "color": "#8c9aa8",
    "textColor": "#111820",
    "descriptionZh": "一发钢钻打罗隐 两发齿轮秒雪灵 \n就算化蝶也惧他 机械克制冰萌地 \n面对电系被抵抗 水火则是它天敌",
    "offense": {
      "0.5": [
        "fire",
        "water",
        "electric",
        "mechanical"
      ],
      "2.0": [
        "ground",
        "ice",
        "cute"
      ]
    },
    "defense": {
      "0.5": [
        "normal",
        "poison",
        "ice",
        "wing",
        "bug",
        "cute",
        "grass",
        "mechanical",
        "dragon",
        "fantasy"
      ],
      "2.0": [
        "fire",
        "water",
        "fighting"
      ]
    }
  },
  {
    "key": "dragon",
    "nameZh": "龙",
    "nameEn": "Dragon",
    "color": "#526fc9",
    "textColor": "#ffffff",
    "descriptionZh": "龙炮对轰真常见 但对机械很乏力\n冰龙萌系克制龙 草火水电翼不怕",
    "offense": {
      "0.5": [
        "mechanical"
      ],
      "2.0": [
        "dragon"
      ]
    },
    "defense": {
      "0.5": [
        "grass",
        "fire",
        "water",
        "electric",
        "wing"
      ],
      "2.0": [
        "ice",
        "dragon",
        "cute"
      ]
    }
  },
  {
    "key": "cute",
    "nameZh": "萌",
    "nameEn": "Cute",
    "color": "#f08aae",
    "textColor": "#2b111b",
    "descriptionZh": "萌打龙武恶魔慌 火毒机械难破防\n毒恶机械没它强 武系虫系能抵抗",
    "offense": {
      "0.5": [
        "fire",
        "poison",
        "mechanical"
      ],
      "2.0": [
        "dragon",
        "fighting",
        "demon"
      ]
    },
    "defense": {
      "0.5": [
        "bug",
        "fighting"
      ],
      "2.0": [
        "demon",
        "poison",
        "mechanical"
      ]
    }
  },
  {
    "key": "normal",
    "nameZh": "普通",
    "nameEn": "Normal",
    "color": "#a6a19a",
    "textColor": "#171717",
    "descriptionZh": "普系憨憨三劲敌 幽系地面机械骑\n武系出手应闪避 幽系战场没问题",
    "offense": {
      "0.5": [
        "ground",
        "ghost",
        "mechanical"
      ],
      "2.0": []
    },
    "defense": {
      "0.5": [
        "ghost"
      ],
      "2.0": [
        "fighting"
      ]
    }
  },
  {
    "key": "water",
    "nameZh": "水",
    "nameEn": "Water",
    "color": "#4f9ed8",
    "textColor": "#ffffff",
    "descriptionZh": null,
    "offense": {
      "0.5": [
        "grass",
        "ice",
        "dragon"
      ],
      "2.0": [
        "fire",
        "ground",
        "mechanical"
      ]
    },
    "defense": {
      "0.5": [
        "fire",
        "mechanical"
      ],
      "2.0": [
        "grass",
        "electric"
      ]
    }
  },
  {
    "key": "fighting",
    "nameZh": "武",
    "nameEn": "Fighting",
    "color": "#c56a3d",
    "textColor": "#ffffff",
    "descriptionZh": "武破普地冰恶械 毒阻虫栏翼萌碍\n翼萌幻袭武系痛 地虫恶魔武能苟",
    "offense": {
      "0.5": [
        "poison",
        "bug",
        "wing",
        "cute",
        "ghost",
        "fantasy"
      ],
      "2.0": [
        "normal",
        "ground",
        "ice",
        "demon",
        "mechanical"
      ]
    },
    "defense": {
      "0.5": [
        "ground",
        "bug",
        "demon"
      ],
      "2.0": [
        "cute",
        "wing",
        "fantasy"
      ]
    }
  },
  {
    "key": "wing",
    "nameZh": "翼",
    "nameEn": "Wing",
    "color": "#7db2d6",
    "textColor": "#0b202e",
    "descriptionZh": "翼系如风电光闪 草虫武系一扫光\n龙电机械地难伤 冰电来袭速躲藏",
    "offense": {
      "0.5": [
        "ground",
        "dragon",
        "electric",
        "mechanical"
      ],
      "2.0": [
        "grass",
        "bug",
        "fighting"
      ]
    },
    "defense": {
      "0.5": [
        "grass",
        "bug",
        "fighting"
      ],
      "2.0": [
        "electric",
        "ice"
      ]
    }
  },
  {
    "key": "ghost",
    "nameZh": "幽灵",
    "nameEn": "Ghost",
    "color": "#7271bb",
    "textColor": "#ffffff",
    "descriptionZh": "幽系破幽和光幻 普系恶系能抵抗\n光幽恶前速撤退 普毒虫武不必慌",
    "offense": {
      "0.5": [
        "normal",
        "demon"
      ],
      "2.0": [
        "light",
        "ghost",
        "fantasy"
      ]
    },
    "defense": {
      "0.5": [
        "normal",
        "poison",
        "bug",
        "fighting"
      ],
      "2.0": [
        "light",
        "ghost",
        "demon"
      ]
    }
  }
] satisfies AttributeMeta[]
