// This file is generated by scripts/import-bwiki-dex.mjs.

export const dataSnapshot = {
  "importedAt": "2026-04-27T16:32:19.847Z",
  "petCount": 465,
  "detailCount": 465,
  "skillCount": 490,
  "skillDetailCount": 490,
  "attributeCount": 18,
  "sourceUrl": "https://wiki.biligame.com/rocom/精灵图鉴",
  "skillSourceUrl": "https://wiki.biligame.com/rocom/技能图鉴",
  "evolutionDetailCount": 27
} as const
